[FIX] - Fix CSV Output from Export Logs
uwblueprint/supportive-housing pull request #118
Opened 2023-06-22 17:38 UTC by owen-sellner

## GitHub Issue link

[Fix CSV Output from Export Logs](https://github.com/uwblueprint/supportive-housing/issues/110)

## Implementation description
* Created `CSVLog` type to remove the properties logId and employeeId exported into the csv
* Combined the first name and last name properties for attnTo and employees 
* Added function `convertToCSVLog` to convert from `LogRecord` to `CSVLog`
* Added the current date to the file name for the CSV file

## Steps to test
1. Verify the export button creates and downloads a CSV file
2. Verify the CSV file contains all of the log records within the date range given
3. Verify the data in the CSV correctly matches the heading it is under

## What should reviewers focus on?
* Can the headers for the CSV file be updated automatically if the properties of `CSVLog` are changed?
* Should the first name and last name of residents be combined?
* What format should the date in the name of the CSV file be? (Currently it is YYYY-MM-DD)

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] If I have made API changes, I have updated the [REST API Docs](https://www.notion.so/uwblueprintexecs/REST-Endpoints-05ce60312bb943439dfda42bb1318536)
- [ ] IF I have made changes to the db/models, I have updated the [Data Models Page](https://www.notion.so/uwblueprintexecs/Data-Models-760f8aa06b244eb0842c079ad77987b0)
- [ ] I have updated other Docs as needed

2023-06-22 21:11 UTC, Safewaan requested changes
thanks for getting this fix out super quickly :D 

There are a few suggestions for how residents are handled, but otherwise, all the asks in the ticket were met :rocket:

2023-06-22 21:11 UTC, safchow commented on frontend/src/types/CSVLog.ts
> +    residentFirstName: string;
we actually don't store the resident's name in a log record, so you can update this to `residentID` (also remove lastName)

2023-06-22 21:11 UTC, safchow commented on frontend/src/helper/CSVConverter.tsx
> +    const headers = ["attnTo", "building", "datetime", "employee", "flagged", "note", "residentFirstName", "residentLastName", "tags"];
should be:
```suggestion
    const headers = ["attnTo", "building", "datetime", "employee", "flagged", "note", "residentID", "tags"];
```

2023-06-22 21:11 UTC, safchow commented on frontend/src/helper/CSVConverter.tsx
> +    residentLastName: logRecord.residentLastName,
change this to id:
```suggestion
    residentId: logRecord.residentId
```

2023-06-22 21:11 UTC, safchow commented on frontend/src/helper/CSVConverter.tsx
> +    residentLastName: logRecord.residentLastName,
and also remove first name

2023-06-23 13:39 UTC, Safewaan approved these changes
lgtm (looks garbage to me)

2023-06-23 13:39 UTC, Safewaan commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
>                      // TODO: Resolve the resident record at some point
you can remove this todo

2023-06-24 00:49 UTC, kevin-pierce commented on frontend/src/types/CSVLog.ts
> +};
nit: I think we might want to run the linter on this 🤓🤓 (we use default ESLint settings, and I think it enforces empty lines in files)

2023-06-24 00:57 UTC, kevin-pierce commented on frontend/src/helper/CSVConverter.tsx
> +    const dateTodayString = dateToday.toLocaleString("fr-CA", {timeZone: "America/Toronto"}).substring(0, 10);
nit: Maybe add a comment above explaining why we're leveraging the `fr-CA` formatter 

For instance,

```suggestion
    // Format the date into YYYY-MM-DD 
    const dateToday = new Date();
    const dateTodayString = dateToday.toLocaleString("fr-CA", {timeZone: "America/Toronto"}).substring(0, 10);
```

2023-06-24 00:57 UTC, kevin-pierce approved these changes
LGTM! The nits are super minor, feel free to ignore them

2023-06-24 01:38 UTC, merged