Require 2FA On Initial Signup for Relief Staff
uwblueprint/supportive-housing pull request #180
Opened 2023-10-12 04:03 UTC by carolynzhang18

## Notion task link

2FA On Initial Signup (https://www.notion.so/uwblueprintexecs/2FA-On-Initial-Signup-f681347ebac54fb0b8bb6fa75c5a34f7)

## Implementation description
* Backend: modify /register route to also return whether the user needs 2FA or not (i.e. Relief Staff or not)
* Frontend: toggle from Signup page to 2FA page upon signup for Relief Staff; redirect to Home page for other users

## Steps to test
1. Login as an Admin and invite 3 new users: (a) an Admin, (b) a Relief staff who requires 2FA (check off this box when creating this user), and (c) a Relief Staff who does not require 2FA (don't check off the box).
2. From the Login page, click "Sign Up" and sign up as each of these 3 users. 
3. For (a) and (c), after signing up, you should be redirected to the Home page immediately. For (b), you should be prompted to complete 2FA with Authy.

## What should reviewers focus on?

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [X] If I have made API changes, I have updated the [REST API Docs](https://www.notion.so/uwblueprintexecs/REST-Endpoints-05ce60312bb943439dfda42bb1318536)
- [X] IF I have made changes to the db/models, I have updated the [Data Models Page](https://www.notion.so/uwblueprintexecs/Data-Models-760f8aa06b244eb0842c079ad77987b0)
- [X] I have documented this PR in the [Production Release Page](https://www.notion.so/uwblueprintexecs/fe28a97bfa5648d3bc3795b32b694acd?v=5565cfb35dcc45bb84f6528cb09517cd)
- [X] I have updated other Docs as needed

2023-10-14 21:19 UTC, connor-bechthold commented on backend/app/rest/auth_routes.py
> +        sign_in_logs_service.create_sign_in_log(auth_dto.id)
I think there's some sign-in logs changes here in the diff that are from this PR (https://github.com/uwblueprint/supportive-housing/pull/170)

Should be fixed by `git pull main` (from `main`), `git checkout carolyn/2fa-on-initial-signup` and then `git merge main` (there may be some conflicts to resolve)

2023-10-15 05:56 UTC, connor-bechthold requested changes
Just a couple things to address but otherwise looks great!

One thing I think that would also be beneficial is to update the naming/locations of some files:
- Right now `Login.tsx` holds `Authy.tsx` and `Credentials.tsx`. I think we can rename `Credentials.tsx` to `Login.tsx` and move it under `forms`. Then, we can rename the old `Login.tsx` to `LoginPage.tsx` and move it under `pages/auth`
- The same thing can be done with what you did here, with `Signup.tsx` and `SignupPage.tsx`

2023-10-15 05:56 UTC, connor-bechthold commented on backend/app/rest/auth_routes.py
> +        sign_in_logs_service.create_sign_in_log(auth_dto.id)
I think there's some sign-in logs changes here in the diff that are from this PR (https://github.com/uwblueprint/supportive-housing/pull/170)

Should be fixed by `git pull main` (from `main`), `git checkout carolyn/2fa-on-initial-signup` and then `git merge main` (there may be some conflicts to resolve)

2023-10-15 05:56 UTC, connor-bechthold commented on frontend/src/components/auth/Signup.tsx
> +      const registerResponse: RegisterResponse = await authAPIClient.register(
The type doesn't need to be included here since it's inferred from the return type of `register` - this can just be:
```const registerResponse =  await authAPIClient.register(...```

2023-10-15 05:56 UTC, connor-bechthold commented on frontend/src/types/AuthTypes.ts
> +export type RegisterResponse = {
There's already a type `LoginResponse` that's the same as this - I'm thinking that can be renamed to something more general like `AuthTokenResponse` and used instead, then we don't need to define a new duplicate type

2023-10-15 05:56 UTC, connor-bechthold commented on frontend/src/APIClients/AuthAPIClient.ts
>      const { data } = await baseAPIClient.post(
Later on in this file the local storage token is set (even when it's not supposed to be) - basically this allows the user to bypass the 2FA page. You can verify this if you signup, go to the 2FA page, and refresh. All you need to do is remove line 106 and you're chilling

2023-10-29 18:27 UTC, phamkelly17 commented on frontend/src/components/forms/Signup.tsx
> +};
nit: move this to the `types` folder

2023-10-29 18:29 UTC, connor-bechthold approved these changes
LGTM!

One thing that I noticed is we still have the `token` field which is in the `Authy` component because of the sign in with google functionality. Since we're not using that anymore, that can be removed (but we can do that in a later ticket so it's not a blocker)

2023-10-29 18:53 UTC, phamkelly17 approved these changes
tested it and everything looks good

2023-11-01 23:44 UTC, merged