Log Records Pagination Rendering
uwblueprint/supportive-housing pull request #183
Opened 2023-10-19 23:40 UTC by achandrabalan

## Notion task link

[Log Records Pagination Rendering](https://www.notion.so/uwblueprintexecs/Log-Records-Pagination-Rendering-4511ae2d72fd4a3ab171e9edb662895f)

## Implementation description
* Deleted log records are immediately removed from modal, not after refresh
* Deleting log records appropriately adjusts pagination and user page number
* If there are no logs, the user will see 'Page 1 of 1' instead of 'Page 0 of 0'

## Steps to test
Deleting a record ..
1. Decrements the total record count by one
2. Initiates toast confirmation message
3. Immediately removes log from modal w/o refresh

Case 1: Deleting record on last page
1. All records below selected record are shifted up
2. If user deletes last record, they are brought to previous page

Case 2: Deleting record on any middle page
1. All records below selected record are shifted up, the top record from the next page is brought to the bottom of the current page to fulfill pagination selection. Ie <10, 25, 50> records are shown
2. If the user deletes the last record, they are brought to the previous page

Case 3: Deleting record on first page
1. All records below selected record are shifted up, if there are multiple pages, the top record from the next page is brought to the bottom of the current page to ensure <10, 25, 50> records are shown.
2. If the user deletes the last record, they remain on the first page

## What should reviewers focus on?
* If there are no logs, should the user see 'Page 0 of 0' or 'Page 1 of 1' ?

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] If I have made API changes, I have updated the [REST API Docs](https://www.notion.so/uwblueprintexecs/REST-Endpoints-05ce60312bb943439dfda42bb1318536)
- [ ] IF I have made changes to the db/models, I have updated the [Data Models Page](https://www.notion.so/uwblueprintexecs/Data-Models-760f8aa06b244eb0842c079ad77987b0)
- [ ] I have documented this PR in the [Production Release Page](https://www.notion.so/uwblueprintexecs/fe28a97bfa5648d3bc3795b32b694acd?v=5565cfb35dcc45bb84f6528cb09517cd)
- [ ] I have updated other Docs as needed

2023-10-21 17:49 UTC, achandrabalan commented
Updated PR to return to 'Page 0 of 0' base case when there are no records to display.

2023-10-25 20:48 UTC, owen-sellner approved these changes
LGTM!!!

2023-10-25 20:48 UTC, owen-sellner commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const newUserPageNum: number = (
![](https://i.pinimg.com/originals/8b/b3/87/8bb387ee878eddeb23baea344d4e13af.gif)

2023-10-29 20:00 UTC, phamkelly17 approved these changes

2023-10-30 03:17 UTC, connor-bechthold requested changes
Looks great! One thing I'm realizing now going through this is I think it makes more sense to keep the page number on the current page when editing (instead of going back to 1)

You'll find what you're looking for in `EditLog.tsx` on lines 266 and 267 - you'll need to pass in the current page number as a prop like you did here as well

2023-10-30 03:17 UTC, connor-bechthold commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const newUserPageNum: number = (
Nit: You can remove the `number` type here

2023-10-30 22:20 UTC, connor-bechthold commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
>      handleDeleteToggle(itemId);
Nit: Delete toggle should be the last thing called in this sequence

2023-11-04 01:11 UTC, connor-bechthold approved these changes
LGTM 🧨

2023-11-04 18:19 UTC, connor-bechthold approved these changes
LGTM 🚒

2023-11-04 22:56 UTC, merged