Residents Directory - Delete Pagination Render
uwblueprint/supportive-housing pull request #185
Opened 2023-10-22 19:42 UTC by achandrabalan

## Implementation description
* Deleting resident automatically removes log from modal, not after refresh
* Deleting resident appropriately updates user page number, resident count, get records

## Steps to test
Deleting a resident..

1. Triggers toast message
2. Decrements resident count by 1
3. If it's the last resident on the page, the user is brought to the previous page. Otherwise, all resident below deleted one are shifted up

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] If I have made API changes, I have updated the [REST API Docs](https://www.notion.so/uwblueprintexecs/REST-Endpoints-05ce60312bb943439dfda42bb1318536)
- [ ] IF I have made changes to the db/models, I have updated the [Data Models Page](https://www.notion.so/uwblueprintexecs/Data-Models-760f8aa06b244eb0842c079ad77987b0)
- [ ] I have documented this PR in the [Production Release Page](https://www.notion.so/uwblueprintexecs/fe28a97bfa5648d3bc3795b32b694acd?v=5565cfb35dcc45bb84f6528cb09517cd)
- [ ] I have updated other Docs as needed

2023-10-25 21:01 UTC, owen-sellner approved these changes
LGTM!!!

2023-10-30 19:17 UTC, connor-bechthold requested changes
beauty saw a few small things to modify but you should be good to go after 👌

2023-10-30 19:17 UTC, connor-bechthold commented on frontend/src/components/forms/CreateResident.tsx
> +  userPageNum,
I don't believe you need to pass in `userPageNum` here

2023-10-30 19:17 UTC, connor-bechthold commented on frontend/src/components/pages/ResidentDirectory/ResidentDirectoryTable.tsx
> +      const newUserPageNum: number = (
`number` can be removed here

2023-10-30 21:35 UTC, connor-bechthold commented on frontend/src/components/pages/ResidentDirectory/ResidentDirectoryTable.tsx
> +              getRecords(userPageNum)
Should also countRecords here in case new records have been added

2023-10-30 22:15 UTC, connor-bechthold commented on frontend/src/components/pages/ResidentDirectory/ResidentDirectoryTable.tsx
> +              getRecords(userPageNum)
You'd want to pass this as a prop to the `EditResident` component and then call it right after the resident is successsfully updated

2023-10-30 22:17 UTC, connor-bechthold commented on frontend/src/components/forms/CreateResident.tsx
> +    setUserPageNum(1);
I would just add this to `getResidents` where you called get and count above on line 74-75 to keep things consistent

2023-11-04 18:04 UTC, connor-bechthold approved these changes
LGTM 💯

2023-11-04 22:54 UTC, merged