Tags Default Sort By Last Modified
uwblueprint/supportive-housing pull request #204
Opened 2023-11-19 19:50 UTC by carolynzhang18

## Notion task link

[Tags Default Sort By Last Modified](https://www.notion.so/uwblueprintexecs/Tags-Default-Sort-By-Last-Modified-1903efa76eea48219081c49d4d15b446)

## Implementation description
* Added a column 'last_modified' to the tags table to automatically record timestamps for create/update operations
* Modified GET route to return tags in order from most to least recently modified

## Steps to test
1. Upgrade database to latest migration: bash ./scripts/flask-db-upgrade.sh
2. In order to test these routes with Postman, first comment out @require_authorization_by_role({"Admin"}) on lines 10, 24, 47, and 71 of backend/app/rest/tags_routes.py.
3. Create a few tags by POSTing to /tags/ (e.g. {"name": “Cool Tag”, "status": "Active”}). 
4. Try GETting from /tags/. The tags you added should be returned in reverse chronological order.
5. Update a tag by PUTting to /tags/[id] (e.g. {"name": “Edited Tag”, "status": "Active”}). 
6. Try GETting from /tags/. The tag you just updated should be the first one returned (and the rest of the tags should also be returned in reverse chronological order).
7. Create & update a few more tags, and check that GETting them still results in the expected order.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] If I have made API changes, I have updated the [REST API Docs](https://www.notion.so/uwblueprintexecs/REST-Endpoints-05ce60312bb943439dfda42bb1318536)
- [ ] IF I have made changes to the db/models, I have updated the [Data Models Page](https://www.notion.so/uwblueprintexecs/Data-Models-760f8aa06b244eb0842c079ad77987b0)
- [ ] I have documented this PR in the [Production Release Page](https://www.notion.so/uwblueprintexecs/fe28a97bfa5648d3bc3795b32b694acd?v=5565cfb35dcc45bb84f6528cb09517cd)
- [ ] I have updated other Docs as needed

2023-11-19 22:18 UTC, achandrabalan commented
LGTM 🥇 
Creating / Updating tags rearranges as expected.

2023-11-19 22:19 UTC, achandrabalan approved these changes

2023-11-22 23:13 UTC, connor-bechthold requested changes
So I left comments on https://github.com/uwblueprint/supportive-housing/pull/198 that can be applied here - we should ensure that this column is set as `nullable=False` so we can always sort by it if needed. Let me know if you have any questions!

2023-11-23 02:06 UTC, connor-bechthold approved these changes

2023-11-23 02:07 UTC, merged