Note, Tags, and Residents Column Formatting
uwblueprint/supportive-housing pull request #208
Opened 2023-11-25 21:49 UTC by owen-sellner

## Notion task link

[Task Name](https://www.notion.so/uwblueprintexecs/2792c3504d744d2b90ff967c32d00961?v=d33629815ecf477ab4e1ff4e33774c32)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Screenshot
![image](https://github.com/uwblueprint/supportive-housing/assets/43042601/346ec37e-c325-457b-88e0-de7607c026fc)

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [ ] If I have made API changes, I have updated the [REST API Docs](https://www.notion.so/uwblueprintexecs/REST-Endpoints-05ce60312bb943439dfda42bb1318536)
- [ ] IF I have made changes to the db/models, I have updated the [Data Models Page](https://www.notion.so/uwblueprintexecs/Data-Models-760f8aa06b244eb0842c079ad77987b0)
- [ ] I have documented this PR in the [Production Release Page](https://www.notion.so/uwblueprintexecs/fe28a97bfa5648d3bc3795b32b694acd?v=5565cfb35dcc45bb84f6528cb09517cd)
- [ ] I have updated other Docs as needed

2023-11-26 19:27 UTC, kevin-pierce commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const noteLimit = 150;
nit: Move this up higher in the file (reduces memory of function invocation) + renaming it to adhere to other constant names

```suggestion
    const NOTE_LIMIT = 150;
```

2023-11-27 19:59 UTC, owen-sellner commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const noteLimit = 150;
I will make the change but just for my own learning how does moving the function reduce memory usage?

2023-12-03 00:39 UTC, connor-bechthold commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const noteLimit = 150;
@owen-sellner basically everytime you invoke this function you're declaring this as a new variable - since it never changes you can put it as a constant at the top of the file so it's only declared once

2023-12-03 02:01 UTC, connor-bechthold requested changes
So I noticed the `zIndex` change may not have worked as intended:
<img width="1210" alt="Screenshot 2023-12-02 at 8 38 52 PM" src="https://github.com/uwblueprint/supportive-housing/assets/64047863/597a4f88-c6c0-4e87-b014-453b0fe99ca2">

Left a couple other small comments but otherwise really well done!!

2023-12-03 02:01 UTC, connor-bechthold commented on frontend/src/components/forms/EditLog.tsx
> +      (item) => logRecord.residents && logRecord.residents.includes(item.label),
hmm curious as to why this was required since we should be guaranteed to have residents on a log record all the time

2023-12-03 02:01 UTC, connor-bechthold commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    if (note && note.length > 0) {
would we have to check for a note here? I don't think there'd ever be a case when a note is empty

2023-12-03 02:01 UTC, connor-bechthold commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const strLength = strArr?.length;
Should be able to get rid of the `?` operator - if there's no results, you'll be passed in an empty array which has a length of 0.

2023-12-03 02:01 UTC, connor-bechthold commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +                      <Td whiteSpace="normal" width="65%">
So ideally the width should remain the same - to get more horizontal space I think we can get away with only displaying the first name of the user in the `Employee` and `Attn To` fields a couple lines below.

2023-12-03 18:03 UTC, kevin-pierce commented on frontend/src/components/forms/EditLog.tsx
> +      (item) => logRecord.residents && logRecord.residents.includes(item.label),
Saw this pop up on Kelly's PR as well ; could it be a linting / warning resolution thing?

2023-12-03 19:32 UTC, owen-sellner commented on frontend/src/components/forms/EditLog.tsx
> +      (item) => logRecord.residents && logRecord.residents.includes(item.label),
Yeah, I am pretty sure it is a lint issue but it wouldn't compose until I added this

2023-12-03 19:33 UTC, owen-sellner commented on frontend/src/components/pages/HomePage/LogRecordsTable.tsx
> +    const strLength = strArr?.length;
It was causing a typescript issue until I added the question mark

2023-12-03 21:49 UTC, phamkelly17 approved these changes
there's a bug though l.o.l

2023-12-03 21:56 UTC, connor-bechthold approved these changes
beauty

2023-12-03 22:20 UTC, merged